name: 🐛 Rapport de Bug
description: Utilisez ce formulaire pour signaler un bug.
title: "Bug: [Titre court du bug]"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: "## 🐞 Description du Bug"
  - type: input
    id: bug-summary
    attributes:
      label: Résumé du Bug
      description: "Fournissez un bref résumé du bug."
      placeholder: "Un court résumé du bug..."
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Description Détaillée
      description: "Décrivez le bug en détail. Incluez ce que vous avez essayé de faire et ce qui s'est produit à la place."
      placeholder: "Quand je fais [...], le système devrait [...], mais [...]"
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Étapes pour Reproduire
      description: "Listez les étapes pour reproduire le bug. Soyez aussi précis que possible."
      placeholder: "1. Aller à '...'\n2. Cliquer sur '...'\n3. Faire défiler jusqu'à '...'\n4. Voir l'erreur"
    validations:
      required: true

  - type: dropdown
    id: operating-system
    attributes:
      label: Système d'Exploitation
      description: "Quel est le système d'exploitation que vous utilisez?"
      options:
        - Windows 10
        - macOS Big Sur
        - Ubuntu 20.04
        - Autre
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: Navigateur
      description: "Si applicable, quel navigateur utilisez-vous?"
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Autre
    validations:
      required: false

  - type: input
    id: browser-version
    attributes:
      label: Version du Navigateur
      description: "Si vous utilisez un navigateur, quelle en est la version?"
      placeholder: "ex. 88"
    validations:
      required: false

  - type: input
    id: app-version
    attributes:
      label: Version de l'Application
      description: "Quelle est la version de l'application où le bug a été observé?"
      placeholder: "ex. 1.2.0"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Contexte Supplémentaire
      description: "Ajoutez tout autre contexte ou captures d'écran concernant le problème ici."
      placeholder: "Informations supplémentaires..."

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: "Cochez pour confirmer que vous avez recherché ce problème et que ce n'est pas un doublon."
      options:
        - label: J'ai vérifié que ce problème n'a pas déjà été signalé ailleurs.
          required: true
